<a href="https://colab.research.google.com/github/xings19/Coursera-ML-AndrewNg-Notes/blob/master/tflearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import tensorflow as tf
print(tf.__version__)

2.4.0


In [3]:
import tensorflow as tf
random_float = tf.random.uniform(shape=(3,3))
print(random_float)

tf.Tensor(
[[0.78635097 0.32468438 0.99661136]
 [0.23080838 0.30224216 0.211007  ]
 [0.06246531 0.97956336 0.5128026 ]], shape=(3, 3), dtype=float32)


```python
tf.random.uniform(
    shape, minval=0, maxval=None, dtype=tf.dtypes.float32, seed=None, name=None
)
```
此函数可以生成随机数，minval和maxval分别为上下界。seed为随机数种子。




下面列举一些常用的操作：

In [9]:
import tensorflow as tf
A = tf.constant([[1., 2.], [3., 4.]])
B = tf.constant([[5., 6.], [7., 8.]])##创建A\B两个常量矩阵（张量）
C = tf.add(A,B)
D = tf.matmul(A,B)
print(C)
print(D)

tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)


很显然add为矩阵加法，matmul为矩阵乘法，经过测试，**matmul为严格的矩阵乘法**

In [14]:
import tensorflow as tf
x = tf.constant(3,dtype=tf.float32)
print(x)
x = tf.Variable(initial_value=3.)
print(x)
with tf.GradientTape() as tape:
  y = tf.square(x)
y_grad = tape.gradient(y,x)
print(y,y_grad)

tf.Tensor(3.0, shape=(), dtype=float32)
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0>
tf.Tensor(9.0, shape=(), dtype=float32) tf.Tensor(6.0, shape=(), dtype=float32)


这段代码展示了tf的自动求导机制，在tf.GradientTape()之下进行的计算步骤都可以用于求导，注意这里的x不再是一个单纯的tensor，这里的x相当于是一个变量，经过测试，这个无法对张量进行求导，但是可以对变量进行求导，因此在求导的时候应该使用变量。

In [20]:
import tensorflow as tf
x = tf.constant([[1. ,2.],[3. ,4.]])
y = tf.constant([[1],[2]],dtype=tf.float32)
w = tf.Variable(initial_value=[[1.],[2.]])
b = tf.Variable(initial_value=1.)
with tf.GradientTape() as tape:
  L = tf.reduce_sum(tf.square(tf.matmul(x,w)+b-y))
w_grad,b_grad = tape.gradient(L,[w,b])
print(w_grad,b_grad)


tf.Tensor(
[[ 70.]
 [100.]], shape=(2, 1), dtype=float32) tf.Tensor(30.0, shape=(), dtype=float32)


上面展示了求偏导，在深度学习中常用。注意这个里面的数据类型应该是float32，但是每次在一个数字后面加小数点都过于麻烦，所以可以考虑在数字较多的地方加上**dtype = tf.float32**